routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::namespace('Frontoffice')->group(function () {
    Route::get('/', 'HomeController@index')->name('frontoffice');
    // Route::resource('users', UserController::class);
    Route::namespace('Auth')->group(function () {
        Route::get('login-user', 'AuthController@showLoginForm')->name('auth-user.login');
		Route::post('login-user', 'AuthController@LoginProcess')->name('auth-user.loginProcess');
        Route::post('auth-user/logout', 'AuthController@logout')->name('auth-user.logout');

        Route::get('/register', 'RegisterController@showRegisterForm')->name('auth-user.register');
        Route::post('/register', 'RegisterController@create')->name('register-form');
        Route::get('/invoice/{id}', 'RegisterController@invoice')->name('register-sukses');
        Route::get('/register/create/{id}/cities', 'RegisterController@getCities')->name('register.cities');
        Route::get('/register/create/{id}/district', 'RegisterController@getDistricts')->name('register.districts');
        Route::get('/register/create/{id}/area', 'RegisterController@getAreas')->name('register.area');

        //Lupa Password
		Route::get('forgot-password', 'ForgotPasswordController@getEmail')->name('auth-user.forgotPassword');
		Route::post('forgot-password', 'ForgotPasswordController@sendEmail')->name('auth-user.sendForgotPassword');
		Route::get('reset-password/{token}', 'ForgotPasswordController@editPassword')->name('auth-user.editPassword');
		Route::put('reset-password', 'ForgotPasswordController@updatePassword')->name('auth-user.updatePassword');
		Route::get('activity-user/{token}', 'ForgotPasswordController@activatedUser')->name('auth-user.activeUser');
    });
    Route::group(['middleware' => ['auth:web']], function(){
		Route::namespace('User')->group(function(){
			Route::get('/dashboard-user', 'DashboardController@index')->name('dashboard-user');
            Route::post('/dashboard-register', 'DashboardController@store')->name('dashboard-register');

            Route::resource('parents', ParentController::class);
            Route::post('parents/approve', 'ParentController@approvalProccess')->name('parent-approval');

            Route::resource('students', StudentController::class);
            Route::post('students/approve', 'StudentController@approvalProccess')->name('student-approval');
            Route::get('/students/create/{id}/cities', 'StudentController@getCities')->name('students.cities');
			Route::get('/students/create/{id}/district', 'StudentController@getDistricts')->name('students.districts');
			Route::get('/students/create/{id}/area', 'StudentController@getAreas')->name('students.area');
		});
	});
});


Route::group(['prefix'     => 'admin', 'namespace'  => 'Backoffice',], function () {

    Route::namespace('Auth')->group(function () {
        Route::get('/', function () {
            return redirect()->route('backoffice.login');
        });
        Route::get('/login', 'LoginController@showLoginForm')->name('backoffice.login');
        Route::post('/login', 'LoginController@login');
        Route::get('/register', 'RegisterController@showRegisterForm')->name('backoffice.register');
        Route::post('/register', 'RegisterController@create');
        Route::post('/logout', 'LoginController@logout')->name('backoffice.logout');

        //Lupa Password
        Route::get('forgot-password', 'ForgotPasswordController@getEmail')->name('backoffice.forgotpassword');
        Route::post('forgot-password', 'ForgotPasswordController@sendEmail')->name('backoffice.forgetpassword.send');
        Route::get('reset-password/{token}', 'ForgotPasswordController@editPassword')->name('backoffice.edit.password');
        Route::put('reset-password', 'ForgotPasswordController@updatePassword')->name('backoffice.update.password');
    
    });
        // Route::get('activity-user/{token}', 'ForgotPasswordController@activatedUser')->name('backoffice.active-user');

    Route::group(['middleware' => ['auth:admin']], function() {
        Route::get('/dashboard', 'DashboardController@index')->name('backoffice.dashboard');
        Route::get('/profile-user/{id}', 'DashboardController@show')->name('backoffice.profile-user');
        Route::get('/change-password/{id}', 'DashboardController@changePassword')->name('backoffice.change-password');
        Route::put('/change-password/{id}', 'DashboardController@updatePassword')->name('backoffice.update-password');
        Route::get('/edit-profile/{id}', 'DashboardController@editProfile')->name('backoffice.edit-profile');
        Route::put('/update-profile{id}', 'DashboardController@updateProfile')->name('backoffice.update-profile');

        Route::namespace('DataRegister')->group(function () {
            Route::get('/data-registrasi', 'RegisterController@index')->name('data-registrasi.index');
            Route::get('/data-registrasi/{id}', 'RegisterController@show')->name('data-registrasi.show');
            Route::post('data-registrasi/approve', 'RegisterController@approvalProccess')->name('data-registrasi.approval');
		});

        Route::namespace('MasterData')->group(function () {
            Route::resource('banks', SysBankController::class);
			Route::get('banks/{bank}/{status}', 'SysBankController@activeNonActive')->name('banks.active_nonactive');

            Route::resource('bank_accounts', SysBankAccountController::class);
			Route::get('bank_accounts/{bank_accounts}/{status}', 'SysBankAccountController@activeNonActive')->name('bank_accounts.active_nonactive');

            Route::resource('categories', SysCategoryController::class);
			Route::get('categories/{category}/{status}', 'SysCategoryController@activeNonActive')->name('categories.active_nonactive');
            Route::post('categories/image_upload', 'SysCategoryController@upload')->name('upload_categories');

            Route::resource('branchs', SysBranchController::class);
			Route::get('branchs/{branch}/{status}', 'SysBranchController@activeNonActive')->name('branchs.active_nonactive');
           
            Route::resource('prosedurs', SysProsedurController::class);
			Route::get('prosedurs/{prosedur}/{status}', 'SysProsedurController@activeNonActive')->name('prosedurs.active_nonactive');

            Route::resource('packet-educations', SysPacketController::class);
			Route::get('packet-educations/{packet_education}/{status}', 'SysPacketController@activeNonActive')->name('packet-educations.active_nonactive');

            Route::resource('category-packets', SysCategoryPacketController::class);
			Route::get('category-packets/{category_packet}/{status}', 'SysCategoryPacketController@activeNonActive')->name('category-packets.active_nonactive');

            Route::resource('educations', SysEducationController::class);
			Route::get('educations/{education}/{status}', 'SysEducationController@activeNonActive')->name('educations.active_nonactive');

            Route::resource('jobs', SysJobsController::class);
			Route::get('jobs/{job}/{status}', 'SysJobsController@activeNonActive')->name('jobs.active_nonactive');

            Route::resource('salaries', SysSalaryController::class);
			Route::get('salaries/{salary}/{status}', 'SysSalaryController@activeNonActive')->name('salaries.active_nonactive');

            Route::resource('sliders', SysSliderController::class);
			Route::get('sliders/{slider}/{status}', 'SysSliderController@activeNonActive')->name('sliders.active_nonactive');

            Route::resource('terms', SysTermController::class);
			Route::get('terms/{term}/{status}', 'SysTermController@activeNonActive')->name('terms.active_nonactive');
            Route::post('terms/image_upload', 'SysTermController@upload')->name('upload_terms');
		});

        Route::namespace('Utilities')->group(function () {
            Route::resource('profile-company', SysProfileCompanyController::class);
            Route::post('profile-company/image_upload', 'SysProfileCompanyController@upload')->name('profile-company.upload');

            Route::resource('faq_categories', SysFaqCategoryController::class);
			Route::get('faq_categories/{faq_category}/{status}', 'SysFaqCategoryController@activeNonActive')->name('faq_categories.active_nonactive');
            Route::post('faq_categories/image_upload', 'SysFaqCategoryController@upload')->name('upload_faq_categories');

            Route::resource('faq_descriptions', SysFaqDescriptionController::class);
			Route::get('faq_descriptions/{description}/{status}', 'SysFaqDescriptionController@activeNonActive')->name('faq_descriptions.active_nonactive');
            Route::post('faq_descriptions/image_upload', 'SysFaqDescriptionController@upload')->name('upload_faq_descriptions');

            Route::resource('brands', SysBrandController::class);
			Route::get('brands/{brand}/{status}', 'SysBrandController@activeNonActive')->name('brands.active_nonactive');
		});

    });
});

app/Http/Controllers/Backoffice/DashboardController.php
<?php

namespace App\Http\Controllers\Backoffice;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Admin;
use App\Models\Student;
use App\Models\Register;
use App\Utilities\HashId;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Hash;
use Carbon, DB, Response, Cache;

class DashboardController extends Controller
{
	use HashId;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$sumStudent = Student::count();
		$sumStudentMan = Student::where('gender', 'Laki-laki')->count();
		$sumStudentWoman = Student::where('gender', 'Perempuan')->count();
		$sumRegister = Register::count();
		
        return view('backoffice.dashboard', compact('sumStudent', 'sumStudentMan', 'sumStudentWoman', 'sumRegister'));
    }

    /**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return \Illuminate\Http\Response
	 */
	public function show($id)
	{
		try {
			$id = $this->decodeHash($id);
			$data = Admin::where('id', $id)->first();
			return view('backoffice.auth.profile.show', compact('data'));
        } catch (\Exception $exc) {
            return redirect()->back()->with('error', 'Terjadi kesalahan saat input coba ulangi lagi');
        }
	}

    public function editProfile($id)
	{
		try {
			$id = $this->decodeHash($id);
			$data = Admin::where('id', $id)->first();
			return view('backoffice.auth.profile.edit', compact('data'));

        } catch (\Exception $exc) {
            return redirect()->back()->with('error', 'Terjadi kesalahan saat input coba ulangi lagi');
        }
	}

    public function updateProfile(Request $request, $id)
	{
		DB::beginTransaction();
		try {
            $validator = Validator::make($request->all(), [
                'image'          		=> 'required|image|mimes:jpg,png,jpeg,gif,svg|max:1000',
            ]);

			if ($validator->fails()) return redirect()->back()->withInput()->withErrors($validator);

            if (!empty($request->file('image'))) {
                $data = Admin::where('id', $id)->first();
				if (\File::exists(public_path('backoffice/assets/images/admin/' . $data->image))) {
                    \File::delete(public_path('backoffice/assets/images/admin/' . $data->image));
				}
				$image = time() . '.' .$request->file('image')->getClientOriginalExtension();
				$destinationPath = public_path('backoffice/assets/images/admin/');
				$request->file('image')->move($destinationPath, $image);

			}

			if(empty($request->file('image'))) {
				$data = Admin::where('id', $id)->first();
				$request['image'] = $data->image;
			}
            $data = Admin::where('id', $id)->first();
			$data->update([
                'name' 			=> isset($request['name']) ? $request->input('name') : null,
                'email' 		=> isset($request['email']) ? $request->input('email') : null,
                'phone_number' 	=> isset($request['phone_number']) ? $request->input('phone_number') : null,
                'gender' 	    => isset($request['gender']) ? $request->input('gender') : null,
                'address' 	    => isset($request['address']) ? $request->input('address') : null,
                'image' 	    => $image,
            ]);

			if (!$data->exists) {
				return redirect()->route('backoffice.dashboard')->with('error', 'Terjadi kesalahan saat input coba ulangi lagi');
			}

			return redirect()->route('backoffice.dashboard')->with('success', 'Admin Berhasil dirubah');

		 	Cache::flush();
			DB::commit();
        } catch (\Exception $exc) {
            DB::rollback();
			return redirect()->route('backoffice.dashboard')->with('error', 'Terjadi kesalahan saat input coba ulangi lagi');
		}
	}

    public function changePassword($id)
	{
		try {
			$id = $this->decodeHash($id);
            $data = Admin::where('id', $id)->first();
			return view('backoffice.auth.profile.change_password', compact('data'));
        } catch (\Exception $exc) {
            return redirect()->back()->with('error', 'Terjadi kesalahan saat input coba ulangi lagi');
        }
	}

	public function updatePassword(Request $request, $id)
	{
		DB::beginTransaction();
		try {
            $validator = Validator::make($request->all(), [
                'password' 			=> 'required|min:3',
                'password_confirmation' 	=> 'required|same:password',
            ]);

            $data = Admin::where('id', $id)->first();
			$data->update([
				'password' => Hash::make($request['password'])
			]);

			if ($validator->fails()) return redirect()->back()->withInput()->withErrors($validator);

			return redirect()->route('backoffice.dashboard')->with('success', 'Password Berhasil dirubah');

		 	Cache::flush();
			DB::commit();
        } catch (\Exception $exc) {
            DB::rollback();
			return redirect()->back()->with('error', 'Terjadi kesalahan saat input coba ulangi lagi');
		}
	}

}

app/Http/Controllers/Backoffice/DataRegister/RegisterController.php
<?php

namespace App\Http\Controllers\Backoffice\DataRegister;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Register;
use App\Models\School;
use App\Utilities\AutoNumber;
use App\Utilities\HashId;
use Illuminate\Support\Facades\Validator;
use DB;
use Carbon\Carbon;

class RegisterController extends Controller
{
    use AutoNumber;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
			$data = Register::orderBy('created_at','DESC')->paginate($request->input('limit', 15));

			return view('backoffice.registrasi.index', compact('data'));
		} catch (\Exception $exc) {
            return $exc;
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            //
        } catch (\Exception $exc) {
            return $exc;
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $data = Register::where('santri_id', $id)->first();
            $school = School::where('santri_id', $id)->first();

            return view('backoffice.registrasi.show', compact('data', 'school'));
        } catch (\Exception $exc) {
            return $exc;
        }
    }

    public function approvalProccess(Request $request)
	{
       	try {
            $id = $request->id;
            $data = Register::where('id', $id)->first();
            $status = $request->input('status');

            if ($status == 'VERIFIED') {
                $approve =  Register::where('id', $id)
                            ->update([ 'status' => $status,
                                        'register_date' => Carbon::now()->format('Y-m-d H:i:s')]);
            }else{
                $approve =  Register::where('id', $id)
                            ->update([ 'status' => $status]);
            }
            
			return redirect()->route('data-registrasi.index');
        } catch (\Exception $exc) {
            return $exc;
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
                // 

        } catch (\Exception $exc) {
            return $exc;
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            // 
           
        } catch (\Exception $exc) {
            return $exc;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

}

resources/views/backoffice/layouts/app.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="{{ asset('frontoffice/assets/images/logo.png') }}">
    
        <title>Admin - Dashboard</title>
        
        <!-- Vendors Style-->
        <link rel="stylesheet" href="{{asset('backoffice/assets/css/vendors_css.css')}}">
        @yield('top-resource')
        <!-- Style-->
        <link rel="stylesheet" href="{{asset('backoffice/assets/css/style.css')}}">
        <link rel="stylesheet" href="{{asset('backoffice/assets/css/skin_color.css')}}">
    
    </head>
    <body class="hold-transition light-skin sidebar-mini theme-primary">
	
        <div class="wrapper">
            @include('backoffice.layouts.header')
            @include('backoffice.layouts.sidebar')
            
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <div class="container">
                    <!-- Main content -->
                    @yield('content')
                    <!-- /.content -->
                </div>
            </div>
            <!-- /.content-wrapper -->
            <footer class="main-footer">
                <div class="container">
                    {{-- <div class="pull-right d-none d-sm-inline-block">
                        <ul class="nav nav-primary nav-dotted nav-dot-separated justify-content-center justify-content-md-end">
                        <li class="nav-item">
                            <a class="nav-link" href="javascript:void(0)">FAQ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Purchase Now</a>
                        </li>
                        </ul>
                    </div> --}}
                    &copy; 2020 <a href="https://www.multipurposethemes.com/">Multipurpose Themes</a>. All Rights Reserved.
                </div>
            </footer>
        </div>
</body>

 <!-- Vendor JS -->
 <script src="{{asset('backoffice/assets/icons/feather-icons/feather.min.js')}}"></script>

 {{-- Perubahan --}}

 <script src="{{asset('backoffice/assets/js/vendors.min.js')}}"></script>
 <script src="{{asset('backoffice/assets/vendor_components/c3/d3.min.js')}}"></script>
 <script src="{{asset('backoffice/assets/vendor_components/c3/c3.min.js')}}"></script>

 <!-- Power BI Admin App -->
 @yield('bottom-resource')

<script>
    $('.btn-active').click(function(){
		var id = $(this).data('id');
        var approve = $(this).data('approve');
        if (approve == "VERIFIED" || approve == "CANCEL"){
            var modal5 = $('#modal5');
            modal5.find('[id=no_register]').val(id);
            modal5.find('[id=status]').val(approve);
            if (approve == "VERIFIED"){
                modal5.find('.modal5-message-body').text("Apakah anda yakin akan menyetujui ?")
            } 
            else if (approve == "CANCEL") {
                modal5.find('.modal5-message-body').text("Apakah anda yakin akan menolak ?")
            }
        } 
        
	});
</script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.js"></script>
 <script src="{{asset('backoffice/assets/js/template.js')}}"></script>
 <script src="{{asset('backoffice/assets/js/demo.js')}}"></script>
 <script src="{{asset('backoffice/assets/js/pages/dashboard.js')}}"></script>
 <script>
     $(document).ready(function(){
		$('.uang').mask('000.000.000.000.000', {reverse: true});
	});
 </script>
</html>

resources/views/backoffice/layouts/header.blade.php
<header class="main-header">
  <div class="d-flex align-items-center logo-box justify-content-between">
      <a href="#" class="waves-effect waves-light nav-link rounded d-none d-md-inline-block mx-10 push-btn" data-toggle="push-menu" role="button">
          <span class="icon-Align-left"><span class="path1"></span><span class="path2"></span><span class="path3"></span></span>
      </a>	
      <!-- Logo -->
      <a href="{{ route('backoffice.dashboard') }}" class="logo">
        <!-- logo-->
        <div class="logo-lg">
            <span class="light-logo">Dashboard Admin</span>
            <span class="dark-logo">Dashboard Admin</span>
        </div>
      </a>	
  </div>  
  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top pl-10">
      <div class="container">
        <!-- Sidebar toggle button-->
        <div class="app-menu">
          <ul class="header-megamenu nav">
              <li class="btn-group nav-item d-md-none">
                  <a href="#" class="waves-effect waves-light nav-link rounded push-btn" data-toggle="push-menu" role="button">
                      <span class="icon-Align-left"><span class="path1"></span><span class="path2"></span><span class="path3"></span></span>
                  </a>
              </li>
              <li class="btn-group nav-item d-none d-xl-inline-block">
                  <a href="#" data-provide="fullscreen" class="waves-effect waves-light nav-link rounded full-screen" title="Full Screen">
                      <i class="icon-Expand-arrows"><span class="path1"></span><span class="path2"></span></i>
                  </a>
              </li>
          </ul> 
        </div>

        <div class="navbar-custom-menu r-side">
          <ul class="nav navbar-nav">		  
              <li class="btn-group d-lg-inline-flex d-none">
                  <div class="app-menu">
                      <div class="search-bx mx-5">
                          {{-- <form>
                              <div class="input-group">
                                <input type="search" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                  <button class="btn" type="submit" id="button-addon3"><i class="ti-search"></i></button>
                                </div>
                              </div>
                          </form> --}}
                      </div>
                  </div>
              </li>

            <!-- User Account-->
            <li class="dropdown user user-menu">
              <a href="#" class="waves-effect waves-light dropdown-toggle" data-toggle="dropdown" title="User">
                  <i class="icon-User"><span class="path1"></span><span class="path2"></span></i>
              </a>
              <ul class="dropdown-menu animated flipInX">
                <li class="user-body">
                  <a class="dropdown-item" href="{{ route('backoffice.profile-user', Auth::guard('admin')->user()->encodeHash(Auth::guard('admin')->user()->id)) }}"><i class="ti-user text-muted mr-2"></i> Profile</a>
                  <a class="dropdown-item" href="{{ route('backoffice.edit-profile', Auth::guard('admin')->user()->encodeHash(Auth::guard('admin')->user()->id)) }}"><i class="ti-wallet text-muted mr-2"></i> Edit Profile</a>
                  <a class="dropdown-item" href="{{ route('backoffice.change-password', Auth::guard('admin')->user()->encodeHash(Auth::guard('admin')->user()->id)) }}"><i class="ti-settings text-muted mr-2"></i> Ubah Password</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="{{ route('backoffice.logout') }}"
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                    <i class="ft-power"></i> Logout
                </a>
                  <form id="logout-form" action="{{ route('backoffice.logout') }}" method="POST" style="display: none;">
                    @csrf
                  </form>
                </li>
              </ul>
            </li>	

          </ul>
        </div>
      </div>
  </nav>
</header>

resources/views/backoffice/layouts/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar-->
    <section class="sidebar">
      <div class="user-profile px-20 py-15">
        <div class="d-flex align-items-center">
          <div class="image">
              @if(!empty(Auth::guard('admin')->user()->image))
                  <img src="{{asset('backoffice/assets/images/admin/'. Auth::guard('admin')->user()->image)}}" class="avatar avatar-lg bg-primary-light" alt="User Image">
              @else
                  <img src="{{asset('frontoffice/assets/images/logo.png')}}" class="avatar avatar-lg bg-primary-light" alt="User Image">
              @endif
          </div>
          
          <div class="info">
            <a class="px-20" data-toggle="dropdown" href="#">Hallo Kak {{Auth::guard('admin')->user()->name}}</a>
          </div>
        </div>
      </div>
        
      <!-- sidebar menu-->
      <ul class="sidebar-menu" data-widget="tree">		
        <li>
          <a href="{{ route('backoffice.dashboard') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Dashboard</span>
          </a>
        </li>
        
        <li class="header">Master Data</li>
        <li>
          <a href="{{ route('banks.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Bank</span>
          </a>
        </li>
        <li>
          <a href="{{ route('bank_accounts.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Akun Bank</span>
          </a>
        </li>
        <li>
          <a href="{{ route('categories.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Kategori</span>
          </a>
        </li>
        <li>
          <a href="{{ route('prosedurs.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Prosedur</span>
          </a>
        </li>
        <li>
          <a href="{{ route('sliders.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Slider</span>
          </a>
        </li>
        <li>
          <a href="{{ route('terms.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Syarat & Ketentuan</span>
          </a>
        </li>
        <li>
          <a href="{{ route('category-packets.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Kategori Paket Pendidikan</span>
          </a>
        </li>
        <li>
          <a href="{{ route('branchs.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Cabang Pendidikan</span>
          </a>
        </li>
        <li>
          <a href="{{ route('packet-educations.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Paket Pendidikan</span>
          </a>
        </li>
        <li>
          <a href="{{ route('educations.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Pendidikan Orangtua</span>
          </a>
        </li>
        <li>
          <a href="{{ route('jobs.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Pekerjaan</span>
          </a>
        </li>
        <li>
          <a href="{{ route('salaries.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Penghasilan</span>
          </a>
        </li>
        <li class="header">Utilities</li>
        <li>
          <a href="{{ route('profile-company.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Profil Perusahaan</span>
          </a>
        </li>
        <li>
          <a href="{{ route('faq_categories.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>FAQ Category</span>
          </a>
        </li>
        <li>
          <a href="{{ route('faq_descriptions.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>FAQ Deskripsi</span>
          </a>
        </li>
        <li>
          <a href="{{ route('brands.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Support Brand</span>
          </a>
        </li>
        <li class="header">Data</li>
        <li>
          <a href="{{ route('data-registrasi.index') }}">
            <i class="icon-Layout-4-blocks"><span class="path1"></span><span class="path2"></span></i>
            <span>Pendaftaran Siswa</span>
          </a>
        </li>
      </ul>
    </section>
</aside>