routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::namespace('Frontoffice')->group(function () {
    Route::get('/', 'HomeController@index')->name('frontoffice');
    // Route::resource('users', UserController::class);
    Route::namespace('Auth')->group(function () {
        Route::get('login-user', 'AuthController@showLoginForm')->name('auth-user.login');
		Route::post('login-user', 'AuthController@LoginProcess')->name('auth-user.loginProcess');
        Route::post('auth-user/logout', 'AuthController@logout')->name('auth-user.logout');

        Route::get('/register', 'RegisterController@showRegisterForm')->name('auth-user.register');
        Route::post('/register', 'RegisterController@create')->name('register-form');
        Route::get('/invoice/{id}', 'RegisterController@invoice')->name('register-sukses');
        Route::get('/register/create/{id}/cities', 'RegisterController@getCities')->name('register.cities');
        Route::get('/register/create/{id}/district', 'RegisterController@getDistricts')->name('register.districts');
        Route::get('/register/create/{id}/area', 'RegisterController@getAreas')->name('register.area');

        //Lupa Password
		Route::get('forgot-password', 'ForgotPasswordController@getEmail')->name('auth-user.forgotPassword');
		Route::post('forgot-password', 'ForgotPasswordController@sendEmail')->name('auth-user.sendForgotPassword');
		Route::get('reset-password/{token}', 'ForgotPasswordController@editPassword')->name('auth-user.editPassword');
		Route::put('reset-password', 'ForgotPasswordController@updatePassword')->name('auth-user.updatePassword');
		Route::get('activity-user/{token}', 'ForgotPasswordController@activatedUser')->name('auth-user.activeUser');
    });
    Route::group(['middleware' => ['auth:web']], function(){
		Route::namespace('User')->group(function(){
			Route::get('/dashboard-user', 'DashboardController@index')->name('dashboard-user');
            Route::post('/dashboard-register', 'DashboardController@store')->name('dashboard-register');

            Route::resource('parents', ParentController::class);
            Route::post('parents/approve', 'ParentController@approvalProccess')->name('parent-approval');

            Route::resource('students', StudentController::class);
            Route::post('students/approve', 'StudentController@approvalProccess')->name('student-approval');
            Route::get('/students/create/{id}/cities', 'StudentController@getCities')->name('students.cities');
			Route::get('/students/create/{id}/district', 'StudentController@getDistricts')->name('students.districts');
			Route::get('/students/create/{id}/area', 'StudentController@getAreas')->name('students.area');
		});
	});
});


Route::group(['prefix'     => 'admin', 'namespace'  => 'Backoffice',], function () {

    Route::namespace('Auth')->group(function () {
        Route::get('/', function () {
            return redirect()->route('backoffice.login');
        });
        Route::get('/login', 'LoginController@showLoginForm')->name('backoffice.login');
        Route::post('/login', 'LoginController@login');
        Route::get('/register', 'RegisterController@showRegisterForm')->name('backoffice.register');
        Route::post('/register', 'RegisterController@create');
        Route::post('/logout', 'LoginController@logout')->name('backoffice.logout');

        //Lupa Password
        Route::get('forgot-password', 'ForgotPasswordController@getEmail')->name('backoffice.forgotpassword');
        Route::post('forgot-password', 'ForgotPasswordController@sendEmail')->name('backoffice.forgetpassword.send');
        Route::get('reset-password/{token}', 'ForgotPasswordController@editPassword')->name('backoffice.edit.password');
        Route::put('reset-password', 'ForgotPasswordController@updatePassword')->name('backoffice.update.password');
    
    });
        // Route::get('activity-user/{token}', 'ForgotPasswordController@activatedUser')->name('backoffice.active-user');

    Route::group(['middleware' => ['auth:admin']], function() {
        Route::get('/dashboard', 'DashboardController@index')->name('backoffice.dashboard');
        Route::get('/profile-user/{id}', 'DashboardController@show')->name('backoffice.profile-user');
        Route::get('/change-password/{id}', 'DashboardController@changePassword')->name('backoffice.change-password');
        Route::put('/change-password/{id}', 'DashboardController@updatePassword')->name('backoffice.update-password');
        Route::get('/edit-profile/{id}', 'DashboardController@editProfile')->name('backoffice.edit-profile');
        Route::put('/update-profile{id}', 'DashboardController@updateProfile')->name('backoffice.update-profile');

        Route::namespace('DataRegister')->group(function () {
            Route::get('/data-registrasi', 'RegisterController@index')->name('data-registrasi.index');
            Route::get('/data-registrasi/{id}', 'RegisterController@show')->name('data-registrasi.show');
            Route::post('data-registrasi/approve', 'RegisterController@approvalProccess')->name('data-registrasi.approval');
		});

        Route::namespace('MasterData')->group(function () {
            Route::resource('banks', SysBankController::class);
			Route::get('banks/{bank}/{status}', 'SysBankController@activeNonActive')->name('banks.active_nonactive');

            Route::resource('bank_accounts', SysBankAccountController::class);
			Route::get('bank_accounts/{bank_accounts}/{status}', 'SysBankAccountController@activeNonActive')->name('bank_accounts.active_nonactive');

            Route::resource('categories', SysCategoryController::class);
			Route::get('categories/{category}/{status}', 'SysCategoryController@activeNonActive')->name('categories.active_nonactive');
            Route::post('categories/image_upload', 'SysCategoryController@upload')->name('upload_categories');

            Route::resource('branchs', SysBranchController::class);
			Route::get('branchs/{branch}/{status}', 'SysBranchController@activeNonActive')->name('branchs.active_nonactive');
           
            Route::resource('prosedurs', SysProsedurController::class);
			Route::get('prosedurs/{prosedur}/{status}', 'SysProsedurController@activeNonActive')->name('prosedurs.active_nonactive');

            Route::resource('packet-educations', SysPacketController::class);
			Route::get('packet-educations/{packet_education}/{status}', 'SysPacketController@activeNonActive')->name('packet-educations.active_nonactive');

            Route::resource('category-packets', SysCategoryPacketController::class);
			Route::get('category-packets/{category_packet}/{status}', 'SysCategoryPacketController@activeNonActive')->name('category-packets.active_nonactive');

            Route::resource('educations', SysEducationController::class);
			Route::get('educations/{education}/{status}', 'SysEducationController@activeNonActive')->name('educations.active_nonactive');

            Route::resource('jobs', SysJobsController::class);
			Route::get('jobs/{job}/{status}', 'SysJobsController@activeNonActive')->name('jobs.active_nonactive');

            Route::resource('salaries', SysSalaryController::class);
			Route::get('salaries/{salary}/{status}', 'SysSalaryController@activeNonActive')->name('salaries.active_nonactive');

            Route::resource('sliders', SysSliderController::class);
			Route::get('sliders/{slider}/{status}', 'SysSliderController@activeNonActive')->name('sliders.active_nonactive');

            Route::resource('terms', SysTermController::class);
			Route::get('terms/{term}/{status}', 'SysTermController@activeNonActive')->name('terms.active_nonactive');
            Route::post('terms/image_upload', 'SysTermController@upload')->name('upload_terms');
		});

        Route::namespace('Utilities')->group(function () {
            Route::resource('profile-company', SysProfileCompanyController::class);
            Route::post('profile-company/image_upload', 'SysProfileCompanyController@upload')->name('profile-company.upload');

            Route::resource('faq_categories', SysFaqCategoryController::class);
			Route::get('faq_categories/{faq_category}/{status}', 'SysFaqCategoryController@activeNonActive')->name('faq_categories.active_nonactive');
            Route::post('faq_categories/image_upload', 'SysFaqCategoryController@upload')->name('upload_faq_categories');

            Route::resource('faq_descriptions', SysFaqDescriptionController::class);
			Route::get('faq_descriptions/{description}/{status}', 'SysFaqDescriptionController@activeNonActive')->name('faq_descriptions.active_nonactive');
            Route::post('faq_descriptions/image_upload', 'SysFaqDescriptionController@upload')->name('upload_faq_descriptions');

            Route::resource('brands', SysBrandController::class);
			Route::get('brands/{brand}/{status}', 'SysBrandController@activeNonActive')->name('brands.active_nonactive');
		});

    });
});

app/Http/Controllers/Backoffice/MasterData/SysBankAccountController.php
<?php

namespace App\Http\Controllers\Backoffice\MasterData;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\SysBankAccount;
use App\Models\SysBank;
use App\Utilities\AutoNumber;
use App\Utilities\HashId;
use Illuminate\Support\Facades\Validator;
use DB, Cache;

class SysBankAccountController extends Controller
{
    use AutoNumber, HashId;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        try {
			$data = SysBankAccount::orderBy('created_at','DESC')->paginate($request->input('limit', 15));

			return view('backoffice.masterdata.bank_accounts.index', compact('data'));
		} catch (\Exception $exc) {
            return $exc;
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bank = SysBank::where('enabled', 1)->get();
		return view('backoffice.masterdata.bank_accounts.create', compact('bank'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        DB::beginTransaction();
        try {
            $validator = Validator::make($request->all(), [
				'account_name' => 'required',
                'bank_id' => 'required',
                'account_number' => 'required|unique:sys_bank_accounts',
			]);

			if ($validator->fails()) return redirect()->back()->withInput()->withErrors($validator);

            $data = SysBankAccount::create([
                'id' 			=> $request['id'] = $this->GenerateAutoNumber('sys_bank_accounts'),
                'account_name'  => isset($request['account_name']) ? $request->input('account_name') : null,
                'account_number'=> isset($request['account_number']) ? $request->input('account_number') : null,
                'bank_id'       => isset($request['bank_id']) ? $request->input('bank_id') : null,
                'enabled' 		=> isset($request['enabled']) ? $request->input('enabled') : null,
            ]);

            Cache::flush();
			DB::commit();
            if (!$data->exists) {
                return redirect()->route('bank_accounts.index')->with('error', 'Terjadi kesalahan saat input coba ulangi lagi');
            }
            return redirect()->route('bank_accounts.index')->with('success', 'Data Berhasil ditambahkan');

		 } catch (\Exception $exc) {
            DB::rollback();
            return $exc;
		 }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $id = $this->decodeHash($id);
            $data = SysBankAccount::where('id', $id)->first();
            $bank = SysBank::where('enabled', 1)->get();

            if (!$data->exists) {
                return redirect()->route('bank_accounts.index')->with('error', 'Terjadi kesalahan saat input coba ulangi lagi');
            }

            return view('backoffice.masterdata.bank_accounts.edit', compact('data', 'bank'));
        } catch (\Exception $exc) {
            return $exc;
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        try {
			$data = SysBankAccount::where('id', $id)->first();
            $data->update([
                'account_name'  => isset($request['account_name']) ? $request->input('account_name') : null,
                'account_number'=> isset($request['account_number']) ? $request->input('account_number') : null,
                'bank_id'       => isset($request['bank_id'     ]) ? $request->input('bank_id'   ) : null,
                'enabled' 		=> isset($request['enabled']) ? $request->input('enabled') : null,
            ]);

            Cache::flush();
			DB::commit();

            if (!$data->exists) {
                return redirect()->route('bank_accounts.index')->with('error', 'Terjadi kesalahan saat input coba ulangi lagi');
            }
            return redirect()->route('bank_accounts.index')->with('success', 'Data Berhasil ditambahkan');
           
        } catch (\Exception $exc) {
            DB::rollback();
            return $exc;
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

	public function activeNonActive($id, $status)
	{
        DB::beginTransaction();
       	try {
            $id = $this->decodeHash($id);
			$activeNonActive = SysBankAccount::where('id', $id)->update([
                'enabled' => $status,
            ]);
			//dd($activeNonActive);

            Cache::flush();
			DB::commit();
            if (!$activeNonActive) {
                return redirect()->route('bank_accounts.index')->with('error', 'Terjadi kesalahan saat input coba ulangi lagi');
            }

			return redirect()->route('bank_accounts.index')->with('success', 'Data Berhasil diubah');
        } catch (\Exception $exc) {
            DB::rollback();
            return $exc;
        }
	}
}

resources/views/backoffice/masterdata/education/create.blade.php
@extends('backoffice.layouts.app')
@section('content')
    		<!-- Main content -->
<section class="content">

<!-- Basic Forms -->
	<div class="box">
		<div class="box-header with-border">
			<h4 class="box-title">Tambah Pendidikan</h4>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			  <div class="row">
				<div class="col">
					<form action="{{route('educations.store')}}" method="POST" class="error">
						@csrf
					  <div class="row">
						<div class="col-12">						
							<div class="form-group">
								<h5>Nama<span class="text-danger">*</span></h5>
								<div class="controls">
									<input type="text" name="name" class="form-control" required value="{{ old('name') }}">
									@if ($errors->has('name'))
										<div class="form-control-feedback text-danger">{{ $errors->first('name') }}</div>
									@endif
								</div>
							</div>
							<div class="form-group">
								<h5>Deskripsi</h5>
								<div class="controls">
									<input type="text" name="description" class="form-control" value="{{ old('description') }}">
									@if ($errors->has('description'))
										<div class="form-control-feedback text-danger">{{ $errors->first('description') }}</div>
									@endif
								</div>
							</div>
							<div class="form-group">
								<h5>Status</h5>
								<div class="controls">
									<label class="switch">
										<input type="checkbox" name="enabled" value="1" class="switch-indicator">
										<span class="switch-indicator" value="0"></span>
                                    	<span class="switch-description" value="1">Aktif</span>
									</label>

										@if ($errors->has('enabled'))
										<div class="form-control-feedback text-danger">{{ $errors->first('enabled') }}</div>
										@endif
								</div>
							</div>
					    </div>
						<div class="text-xs-right">
							<a href="{{ route('educations.index') }}" type="button" class="waves-effect waves-light btn btn-outline btn-secondary mb-5"><i class="ti-trash"></i>&nbsp;Batal</a><span></span>
							<button type="submit" class="waves-effect waves-light btn btn-outline btn-primary mb-5"><i class="ti-save-alt"></i>&nbsp;Simpan</button>		
						</div>
					</form>

				</div>
				<!-- /.col -->
			  </div>
			  <!-- /.row -->
			</div>
		<!-- /.box-body -->
	</div>
	<!-- /.box -->
</section>
<!-- /.content -->

@endsection

resources/views/backoffice/masterdata/education/edit.blade.php
@extends('backoffice.layouts.app')
@section('content')
    		<!-- Main content -->
<section class="content">

<!-- Basic Forms -->
	<div class="box">
		<div class="box-header with-border">
			<h4 class="box-title">Edit Pendidikan</h4>
		</div>
		<!-- /.box-header -->
		<div class="box-body">
			  <div class="row">
				<div class="col">
					<form action="{{route('educations.update',$data->id)}}" method="POST" class="error">
						@csrf
						{{ method_field('PUT') }}
					  <div class="row">
						<div class="col-12">						
                            <div class="form-group">
								<h5>Nama<span class="text-danger">*</span></h5>
								<div class="controls">
									<input type="text" name="name" class="form-control" required value="{{$data->name}}">
									@if ($errors->has('name'))
										<div class="form-control-feedback text-danger">{{ $errors->first('name') }}</div>
									@endif
								</div>
							</div>
							<div class="form-group">
								<h5>Deskripsi</h5>
								<div class="controls">
									<input type="text" name="description" class="form-control" value="{{$data->description}}">
									@if ($errors->has('description'))
										<div class="form-control-feedback text-danger">{{ $errors->first('description') }}</div>
									@endif
								</div>
							</div>
							<div class="form-group">
								<h5>Status</h5>
								<div class="controls">
									<label class="switch">
										<input type="checkbox" name="enabled" value="1" {{ $data->enabled == 1 ? 'checked="checked"' : '' }} class="switch-indicator">
										<span class="switch-indicator" value="0"></span>
                                    	<span class="switch-description" value="1">Aktif</span>
									</label>

										@if ($errors->has('enabled'))
										<div class="form-control-feedback text-danger">{{ $errors->first('enabled') }}</div>
										@endif
								</div>
							</div>
						</div>
						
					  </div>
						<div class="text-xs-right">
							<a href="{{route('educations.index')}}" type="button" class="waves-effect waves-light btn btn-outline btn-secondary mb-5"><i class="ti-trash"></i>&nbsp;Batal</a><span></span>
							<button type="submit" class="waves-effect waves-light btn btn-outline btn-primary mb-5"><i class="ti-save-alt"></i>&nbsp;Simpan</button>		
						</div>
					</form>

				</div>
				<!-- /.col -->
			  </div>
			  <!-- /.row -->
			</div>
		<!-- /.box-body -->
	</div>
	<!-- /.box -->
</section>
<!-- /.content -->

@endsection

resources/views/backoffice/masterdata/education/index.blade.php
@extends('backoffice.layouts.app')
@section('content')
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="box">
                @if(Session::has('success'))
                <div class="alert alert-outline alert-success" role="alert">
                    <i data-feather="check" class="mg-r-10"></i> {{Session::get('success')}}
                </div>
                @elseif((Session::has('error')))
                <div class="alert alert-outline alert-danger" role="alert">
                    <i data-feather="alert-circle" class="mg-r-10"></i> {{Session::get('error')}}
                </div>
                @endif
                <div class="box-header with-border">
                    <h3 class="box-title">Data Pendidikan</h3>
                    <a href="{{ route('educations.create') }}"
                        class="waves-effect waves-light btn btn-outline btn-primary float-right mb-2">Tambah Data</a>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                @if(count($data) > 0)
                    <div class="table-responsive">
                        <div id="example_wrapper" class="dataTables_wrapper container-fluid dt-bootstrap4">
                                {{-- <form method="POST" action="">
                                    @csrf
                                <div id="example_filter" class="dataTables_filter">
                                <label>Search:<input type="search" name="param" class="form-control form-control-sm" placeholder="Input Name" aria-controls="example">
                                </label>
								<button type="submit" class="btn btn-primary btn-sm"><i class="fa fa-search"></i></button>
                            </div>
							</form> --}}
                            <table class="table b-1 border-primary">
                                <thead class="bg-primary">
                                    <tr>
                                        <th>No</th>
                                        <th>Nama</th>
                                        <th>Deskripsi</th>
                                        <th>Status</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                    $i = 1;
                                    @endphp
                                    @foreach($data as $row)
                                    <tr>
                                        <td>{{$i++}}</td>
                                        <td>{{ $row->name }}</td>
                                        <td>{{ $row->description }}</td>
                                        <td>
                                            @if ($row->enabled == 1)
                                            <span class="badge badge-success">Active</span>
                                            @else
                                            <span class="badge badge-secondary">Not Active</span>
                                            @endif
                                        </td>
                                        <td class="btn-group">
                                            <a href="{{ route('educations.edit', $row->encodeHash($row->id)) }}"
                                                class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                                            @if($row->enabled == 1)
                                            <a href="{{ route('educations.active_nonactive', [$row->encodeHash($row->id), 0]) }}"
                                                class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></a>
                                            @else
                                            <a href="{{ route('educations.active_nonactive', [$row->encodeHash($row->id), 1]) }}"
                                                class="btn btn-primary btn-sm"><i class="fa fa-undo"></i></a>
                                            @endif
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $data->links('backoffice.layouts.pagination') }}
                        </div>
                        <!-- /.box-body -->
                    </div>
                </div>
                @else
                    <H2>Data Tidak Ditemukan!</H2>
                @endif
            </div>
        </div>
    </div>
</section>

@endsection